### ISSUE TITLE
Redo charts notebook based on new charts user guide

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh-notebooks#13]
revamp the charts section
- new features
- new syntax
- have a text note about any new limitations / current limitations 
- how to use your old charts
- plans / upgrades.

**Comment by jcull** [comment]
Current texas.ipynb missing following necessary code from bk09:

TOOLS="pan,wheel_zoom,box_zoom,reset,hover,save"

p = figure(title="Texas Unemployment 2009", tools=TOOLS)

Also has import of output_file, but executes output_notebook()

**Comment by bryevdv** [comment]
charts gone
