### ISSUE TITLE
Mention `add_glyph`, `add_tools`, `add_layout`

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh-notebooks#19]
I think it's good to mention the methods "add_glyph, add_tools, add_layout" which can be used on a chart, figure, or plot.

Mention in each briefly and then repetition will kick in? Or don't mention in charts as you're just getting going?

**Comment by eldobbins** [comment]
These are covered extensively now in Tutorial 09 Models and Primitives.  Close issue?

**Comment by bryevdv** [comment]
thanks @eldobbins
