### ISSUE TITLE
Broken examples in the tutorials

### ISSUE THREAD

**Issue by bsipocz** [bokeh/bokeh-notebooks#34]
I'm browsing around for some functionalities and looking at the tutorials always proved to be useful for this. However a I'm running into some issues that may be worth reporting/fixing. 

My versions:
```
Python 3.4.5
IPython - 4.2.0
Pandas - 0.18.0
Bokeh - 0.12.1dev2
```

- [ ] Hoover example in ``03 - styling,ipynb`` is not working: The plot is static for me.
- [ ] Jupyter interactors example in ``04 - interactions.ipynb``: the widget doesn't snow up, I got only this ``<function __main__.update>`` as output
- [ ] WMTS Tile Source figures are broken as the tile access has been discontinued.
- [ ] More recent releases of ``datashader`` are not uploaded to pypi? (I didn't check the notebook as still have some installing issues).
- [ ]  Second cell in ``A2 - Building gapminder.ipynb`` raises several deprecation warnings, and later cells raises ``TypeErrors``, basically none of the cells produce a single plot.

**Comment by bryevdv** [comment]
> Hoover example in 03 - styling,ipynb is not working: The plot is static for me.

It's working for me here: http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/tutorial/03%20-%20styling.ipynb#Selection-and-non-selection-visuals Are you saying it is not working for you there? It also worked perfectly during the SciPy tutorials last week in local notebooks. Can you clarify what you mean by "static" ?

> Jupyter interactors example in 04 - interactions.ipynb: the widget doesn't snow up, I got only this <function __main__.update> as output

That seems to be a jupyter interactors issue, I'm not sure what we can do about it

> WMTS Tile Source figures are broken as the tile access has been discontinued. 

Also outside our control, it was noted during the tutorial as the policy change happened to start that morning. 

> More recent releases of datashader are not uploaded to pypi? (I didn't check the notebook as still have some installing issues).

 AFAIK they are, ping @jbednar 

> Second cell in A2 - Building gapminder.ipynb raises several deprecation warnings, and later cells raises TypeErrors, basically none of the cells produce a single plot.

This notebook was removed from the TOC in the index notebook. I suppose it should be deleted completely to avoid confusion

**Comment by bsipocz** [comment]
> Hoover example in 03 - styling,ipynb is not working: The plot is static for me.

@bryevdv - If I hooverover nothing happens. I remember seeing it working before with a previous bokeh version.

**Comment by bryevdv** [comment]
It's definitely working for myself and others. Can you file an issue with detailed version information (OS, browser, libraries) as well as any browser javascript console output

**Comment by jbednar** [comment]
No version of datashader is available on PyPI.  There is a dummy "0.1.0" entry for datashader on the PyPI website, but there are no associated installable files, because PyPI/pip cannot manage the binary dependencies that datashader requires for it to have acceptable performance.  I've updated that entry to clarify that it's there only to reserve the name "datashader" so that other projects don't cause confusion by choosing that name.

**Comment by bsipocz** [comment]
Firefox 47.0, OSX 10.10.5. Tried it with Safari 9.1.1, no luck there either.
Lib versions:
```
Python 3.4.5
IPython - 4.2.0
Pandas - 0.18.0
Bokeh - 0.12.1dev2
```
The JS console output I guess is this one, cleared right before running this cell:

```
Bokeh: BokehJS plotting callback run at Date 2016-07-19T17:11:40.970Z main.min.js:81:9
Bokeh: JS/Python version mismatch bokeh-0.12.1dev2.min.js:67:11126
Bokeh: Library versions: JS (0.12.0)  /  Python (0.12.1dev2) bokeh-0.12.1dev2.min.js:67:11126
Bokeh: all callbacks have finished main.min.js:16:7
Bokeh: Registering Jupyter comms for target 25ed44fb-d309-4dee-b381-ea68af66e958 bokeh-0.12.1dev2.min.js:67:11199
TypeError: b is undefined
Bokeh</<["models/glyphs/circle"]</o</e.prototype._hit_span()
 bokeh-0.12.1dev2.min.js:8
Bokeh</<["models/renderers/renderer"]</a</e.prototype.hit_test()
 bokeh-0.12.1dev2.min.js:14
Bokeh</<["models/renderers/glyph_renderer"]</o</e.prototype.hit_test()
 bokeh-0.12.1dev2.min.js:14
Bokeh</<["common/selection_manager"]</o</e.prototype.inspect()
 bokeh-0.12.1dev2.min.js:3
Bokeh</<["models/tools/inspectors/hover_tool"]</s</e.prototype._inspect()
 bokeh-0.12.1dev2.min.js:17
Bokeh</<["models/tools/inspectors/hover_tool"]</s</e.prototype._clear()
 bokeh-0.12.1dev2.min.js:17
Bokeh</<["models/tools/inspectors/hover_tool"]</s</e.prototype._move()
 bokeh-0.12.1dev2.min.js:17
Bokeh</<.backbone</</</y()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<.backbone</</</g()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<.backbone</</</p()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<.backbone</</</c.trigger()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<["common/ui_events"]</s</e.prototype._mouse_move()
 bokeh-0.12.1dev2.min.js:3
Bokeh</<["common/ui_events"]</s</e.prototype._hammer_element/</<()
 bokeh-0.12.1dev2.min.js:3
Bokeh</<.jquery</</st.event.dispatch()
 bokeh-0.12.1dev2.min.js:66
.jquery_event_drag</o.dispatch()
 bokeh-widgets-0.12.1dev2.min.js:171
Bokeh</<.jquery</</st.event.add/m.handle()
 bokeh-0.12.1dev2.min.js:65
 bokeh-0.12.1dev2.min.js:8:4057
TypeError: b is undefined
Bokeh</<["models/glyphs/circle"]</o</e.prototype._hit_span()
 bokeh-0.12.1dev2.min.js:8
Bokeh</<["models/renderers/renderer"]</a</e.prototype.hit_test()
 bokeh-0.12.1dev2.min.js:14
Bokeh</<["models/renderers/glyph_renderer"]</o</e.prototype.hit_test()
 bokeh-0.12.1dev2.min.js:14
Bokeh</<["common/selection_manager"]</o</e.prototype.inspect()
 bokeh-0.12.1dev2.min.js:3
Bokeh</<["models/tools/inspectors/hover_tool"]</s</e.prototype._inspect()
 bokeh-0.12.1dev2.min.js:17
Bokeh</<["models/tools/inspectors/hover_tool"]</s</e.prototype._move()
 bokeh-0.12.1dev2.min.js:17
Bokeh</<.backbone</</</y()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<.backbone</</</g()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<.backbone</</</p()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<.backbone</</</c.trigger()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<["common/ui_events"]</s</e.prototype._mouse_move()
 bokeh-0.12.1dev2.min.js:3
Bokeh</<["common/ui_events"]</s</e.prototype._hammer_element/</<()
 bokeh-0.12.1dev2.min.js:3
Bokeh</<.jquery</</st.event.dispatch()
 bokeh-0.12.1dev2.min.js:66
.jquery_event_drag</o.dispatch()
 bokeh-widgets-0.12.1dev2.min.js:171
Bokeh</<.jquery</</st.event.add/m.handle()
 bokeh-0.12.1dev2.min.js:65
 bokeh-0.12.1dev2.min.js:8:4057
TypeError: b is undefined
Bokeh</<["models/glyphs/circle"]</o</e.prototype._hit_span()
 bokeh-0.12.1dev2.min.js:8
Bokeh</<["models/renderers/renderer"]</a</e.prototype.hit_test()
 bokeh-0.12.1dev2.min.js:14
Bokeh</<["models/renderers/glyph_renderer"]</o</e.prototype.hit_test()
 bokeh-0.12.1dev2.min.js:14
Bokeh</<["common/selection_manager"]</o</e.prototype.inspect()
 bokeh-0.12.1dev2.min.js:3
Bokeh</<["models/tools/inspectors/hover_tool"]</s</e.prototype._inspect()
 bokeh-0.12.1dev2.min.js:17
Bokeh</<["models/tools/inspectors/hover_tool"]</s</e.prototype._clear()
 bokeh-0.12.1dev2.min.js:17
Bokeh</<["models/tools/inspectors/hover_tool"]</s</e.prototype._move_exit()
 bokeh-0.12.1dev2.min.js:17
Bokeh</<.backbone</</</y()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<.backbone</</</g()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<.backbone</</</p()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<.backbone</</</c.trigger()
 bokeh-0.12.1dev2.min.js:23
Bokeh</<["common/ui_events"]</s</e.prototype._mouse_exit()
 bokeh-0.12.1dev2.min.js:3
Bokeh</<["common/ui_events"]</s</e.prototype._hammer_element/</<()
 bokeh-0.12.1dev2.min.js:3
Bokeh</<.jquery</</</st.event.special[t].handle()
 bokeh-0.12.1dev2.min.js:66
Bokeh</<.jquery</</st.event.dispatch()
 bokeh-0.12.1dev2.min.js:66
.jquery_event_drag</o.dispatch()
 bokeh-widgets-0.12.1dev2.min.js:171
Bokeh</<.jquery</</st.event.add/m.handle()
 bokeh-0.12.1dev2.min.js:65
 bokeh-0.12.1dev2.min.js:8:4057
```

**Comment by bsipocz** [comment]
@jbednar - Fair enough, thanks for the clarification.

**Comment by bryevdv** [comment]
Oh right, sorry, I responded to quickly and missed the PyPI part

@bsipocz  my apologies for not being clear, I was suggesting an issue on the Bokeh main repo issue tracker.

**Comment by bsipocz** [comment]
@bryevdv - Oh, I'm sorry it seems I didn't read it properly.

**Comment by markkernke** [comment]
> > Jupyter interactors example in 04 - interactions.ipynb: the widget doesn't snow up, I got only this as output

> That seems to be a jupyter interactors issue, I'm not sure what we can do about it

I found a solution for this by using the following via the command line before running _jupyter notebook_ to start the server:
jupyter nbextension enable --py --sys-prefix widgetsnbextension

**Comment by bryevdv** [comment]
I'm going to go ahead an close this. I think all of the questions have either been answered above, or in recent work to improve notebook integration for `0.12.2`. To summarize:

* hover and interactors have been working consistently (in 3-4 tutorials in the last month) 
* datashader is available via conda or source because of non-python dependencies
* gapminder notebook has been removed

**Comment by bsipocz** [comment]
Thanks @bryevdv.
