### ISSUE TITLE
gapminder example in notebook

### ISSUE THREAD

**Issue by toasteez** [bokeh/bokeh-notebooks#37]
I'm trying to find a working example of Bokeh with a slider.  Are there any available?

**Comment by bryevdv** [comment]
That's a very broad question. A Jupyter / ipywidgets slider? A Bokeh slider with JS callbacks? or with server callbacks? In any case, the proper place for general support questions is the public mailing list, please direct your questions there:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

There is a larger audience of people who can potentially answer, and it allows us to keep the tracker for  reserved for bug and feature issues.
