### ISSUE TITLE
ichart.yahoo.com discontinued by Yahoo

### ISSUE THREAD

**Issue by eldobbins** [bokeh/bokeh-notebooks#43]
In section 07. Sharing and Embedding of the Bokeh Tutorial, the first code example pulls data from icharts.yahoo.com using the URL  http://ichart.yahoo.com/table.csv?s=AAPL&a=0&b=1&c=2000&d=0&e=1&f=2015

Unfortunately, this service has been discontinued by the Yahoo finance team sometime around May, 2017, according to info in this thread: https://forums.yahoo.net/t5/Yahoo-Finance-help/Is-Yahoo-Finance-API-broken/m-p/251312#M3123

There are rumors that Google offers a similar service.  Perhaps the code could be updated to use Google instead of Yahoo?

**Comment by bryevdv** [comment]
Entirely possible, the core dev team is pretty underwater with work right now so if you have the ability to submit a PR to update the notebook it would be valuable and appreciated.

**Comment by eldobbins** [comment]
I found a couple other little bugs and could update those.  However, I'm
new to GitHub and will have to figure out how to do it.  I will try, though.

Liz

On Thu, Jul 20, 2017 at 12:25 PM, Bryan Van de Ven <notifications@github.com

**Comment by bryevdv** [comment]
That would be super helpful. Happy to help with questions, etc. The rough outline is this:

* fork the repo to your GitHub acct (button on the web UI)
* make a local clone of your fork (`git clone <repo url>`
* make branch on your local clone  (`git checkout -b <branch name>`)
* make changes on the branch
* commit an push the branch back to GitHub (use `git add` then `git commit` then `git push`)
* make a PR from the branch on your fork, to the master branch of main repo (web UI)

There is also a tutorial that seems pretty good with more details here: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by eldobbins** [comment]
PR #44 addresses this.
