### ISSUE TITLE
2nd Interactive Exploration example in Ch 12 (Holoviews) gives Value Error

### ISSUE THREAD

**Issue by eldobbins** [bokeh/bokeh-notebooks#46]
I do not understand what the call is trying to do, so cannot fix it myself.
Here is part of the Traceback:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-ccc66c56bd02> in <module>()
      2 keys = [(p,f) for p in phases for f in freqs]
      3 
----> 4 hv.HoloMap([(k, hv.Image(sine(grid, *k))) for k in keys], **dims) + hv.HoloMap([(k, hv.Curve(zip(dist, sine(dist**2, *k)),vdims=dims['vdims'])) for k in keys], **dims)
...
/Users/EDobbins/anaconda2/lib/python2.7/site-packages/param/__init__.pyc in _check_bounds(self, val)
   1174             if min_length is not None and max_length is not None:
   1175                 if not (min_length <= l <= max_length):
-> 1176                     raise ValueError("%s: list length must be between %s and %s (inclusive)"%(self._attrib_name,min_length,max_length))
   1177             elif min_length is not None:
   1178                 if not min_length <= l:

ValueError: vdims: list length must be between 0 and 0 (inclusive)

Also, there are 2 examples which use deprecated options which can be changed when the bug is fixed.

The first code block refers to:
hv.notebook_extension('bokeh'=True)
which should be changed to:
hv.extension('bokeh')

The 2nd example in the External Data Sources give a warning that the mdims argument should be changed to groupby.

**Comment by bryevdv** [comment]
thinking more on this I think perhaps we should simply provide links to officially maintained HV materials, which are extensive:

https://github.com/ioam/scipy-2017-holoviews-tutorial

**Comment by bryevdv** [comment]
Closing, the HV materials in this repo will be pared down considerably, and point to official HV project resources for further materials.
