### ISSUE TITLE
Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0

### ISSUE THREAD

**Issue by rissom** [bokeh/bokeh-notebooks#52]
Hi! I am new to Bokeh and wanted to try it out. I installed it with pip and cloned the bokeh-notebooks repository. I went to the 5 min Overview. The first three steps run through, the 4th step:
```
p = figure(width=500, height=500)
p.circle(x, y, size=7, color="firebrick", alpha=0.5)
show(p)
```
doesn't show a picture. Instead I get an error 404 in the browser console. And the following warning:

> Failed to load resource: the server responded with a status of 404 (Not Found)
main.min.js:34110 Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
(anonymous) @ main.min.js:34110

Do I have to install one of the two packages? If yes, which one should I use?

**Comment by rissom** [comment]
Ok, a "pip3 install widgetsnbextension" did the trick. But there should be a note somewhere.

**Comment by bryevdv** [comment]
@rissom `ipywidgets` is not part of Bokeh, and not used by Bokeh. A very few examples do use them, to show how interop might work. There is nothing in the code above that would require `ipywidgets` be installed, and I have run that notebook without `ipywidgets` installed many times, and verified it again just now:

<img width="638" alt="screen shot 2017-11-30 at 09 04 58" src="https://user-images.githubusercontent.com/1078448/33437458-a1085d0a-d5ad-11e7-8b32-cfb6d038ef10.png">

 I have to conclude there is something specific to your local jupyter installation or configuration that is causing this problem.

**Comment by rissom** [comment]
Thank you for looking into this. Sorry, I also don't know what caused this. I used the notebook from the repository. Jupyter was installed with homebrew on a mac. I used python3.
It probably is somehow related with how the javascript libraries are served. Since it was a javascript error. But I really have no idea. It works now for me.
