### ISSUE TITLE
Texas Unemployment Example

### ISSUE THREAD

**Issue by DWSimmons** [bokeh/bokeh-notebooks#53]
In https://github.com/bokeh/bokeh-notebooks/blob/master/tutorial/09%20-%20Geographic%20Plots.ipynb in cell 1
```
It is often useful to be able to relate datasets with their real-world context. You can plot geographic data just like any other type of data, as in the Texas Unemployment example, but Bokeh also Bokeh provides several specialized mechanisms for plotting data in geographic coordinates:
```
Texas Unemployment example is linked to http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/gallery/texas.ipynb which no longer exists.  I believe new link is https://bokeh.pydata.org/en/latest/docs/gallery/texas.html

https://github.com/bokeh/bokeh-notebooks/pull/54

**Comment by bryevdv** [comment]
closed by #54
