### ISSUE TITLE
WMTSTileSource import error

### ISSUE THREAD

**Issue by DWSimmons** [bokeh/bokeh-notebooks#55]
Cell 2 has
`from bokeh.tile_providers import WMTSTileSource` which returns 
`ImportError: cannot import name 'WMTSTileSource`

I believe the WMTSTileSource it's looking for
`class WMTSTileSource(MercatorTileSource):` is at
https://github.com/bokeh/bokeh/blob/359a9fa8e2cb0406bd06b57e233b221cb916fae8/bokeh/models/tiles.py#L95

**Comment by bryevdv** [comment]
That's correct, at some point `tile_providers.py` was refined to only expose pre-configured sources such as carto and stamen. A small PR to update the import would be appreciated!

**Comment by bryevdv** [comment]
This was fixed

**Comment by zarifaziz** [comment]
Where was this fixed? I'm stil getting errors

ImportError: cannot import name 'get_provider' from 'bokeh.tile_providers' (unknown location)

**Comment by bryevdv** [comment]
@zarifaziz That's not the same error message as above, and respectfully, please don't ask the same thing in multiple project sites simultaneously. It creates unnecessary burden for maintainers. I answered in https://github.com/bokeh/bokeh/issues/9402
