### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by gafeng** [bokeh/bokeh-notebooks#56]
In file quickstart.ipynb, there is a typo at the first sentense of session "Bokeh Application". It should be "easily", not "eqsily", I guess.

In file “04 - Data Sources and Transformations.ipynb”, there is a typo between In[7] and In[8]. The "glhph methods" should be "glyph", I guess.

In file "05 - Presentation Layouts.ipynb", There is a typo in 3rd sentense "Boeh plots can be individually embedded in HTML documents". It should be "Bokeh", I guess.

**Comment by bryevdv** [comment]
@gafeng would you like to submit a PR to fix these? They are simple enough that it could probably be done directly drive the GH UI and woukd be a great help

**Comment by bryevdv** [comment]
fixed in #58
