### ISSUE TITLE
bokeh-notebooks - gallery:  Can not open the notebooks  .ipynb in the gallery 

### ISSUE THREAD

**Issue by an100** [bokeh/bokeh-notebooks#6]
bokeh-notebooks - gallery  Can not open the notebooks  .ipynb in the gallery 
I am in windows 7 - bokeh version 0.8.1

2015-03-21 14:41:04.543 [NotebookApp] WARNING | Unreadable Notebook: C:\Users\Amit\Documents\IPython Notebooks\S00_Blaze_Bokeh\bokeh-notebooks\gallery
\bollinger.ipynb name 'NBFormatError' is not defined
WARNING:tornado.access:400 GET /api/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/gallery/bollinger.ipynb?_=1426948863684 (127.0.0.1) 37.00ms referer=http
://localhost:8888/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/gallery/bollinger.ipynb
2015-03-21 14:41:15.954 [NotebookApp] WARNING | Unreadable Notebook: C:\Users\Amit\Documents\IPython Notebooks\S00_Blaze_Bokeh\bokeh-notebooks\gallery
\burtin.ipynb name 'NBFormatError' is not defined
WARNING:tornado.access:400 GET /api/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/gallery/burtin.ipynb?_=1426948875024 (127.0.0.1) 45.00ms referer=http://
localhost:8888/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/gallery/burtin.ipynb
2015-03-21 14:41:25.904 [NotebookApp] WARNING | Unreadable Notebook: C:\Users\Amit\Documents\IPython Notebooks\S00_Blaze_Bokeh\bokeh-notebooks\gallery
\linked_brushing.ipynb name 'NBFormatError' is not defined
WARNING:tornado.access:400 GET /api/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/gallery/linked_brushing.ipynb?_=1426948885363 (127.0.0.1) 43.50ms refere
r=http://localhost:8888/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/gallery/linked_brushing.ipynb
2015-03-21 14:41:52.151 [NotebookApp] WARNING | Notebook S00_Blaze_Bokeh/bokeh-notebooks/tutorial/exercises/advanced/01-les-miserables.ipynb is not tr
usted

2015-03-21 14:48:49.845 [NotebookApp] WARNING | Unreadable Notebook: C:\Users\Amit\Documents\IPython Notebooks\S00_Blaze_Bokeh\bokeh-notebooks\index.i
pynb name 'NBFormatError' is not defined
WARNING:tornado.access:400 GET /api/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/index.ipynb?_=1426949329243 (127.0.0.1) 30.00ms referer=http://localhost
:8888/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/index.ipynb
2015-03-21 14:49:29.277 [NotebookApp] WARNING | Unreadable Notebook: C:\Users\Amit\Documents\IPython Notebooks\S00_Blaze_Bokeh\bokeh-notebooks\quickst
art\quickstart.ipynb name 'NBFormatError' is not defined
WARNING:tornado.access:400 GET /api/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/quickstart/quickstart.ipynb?_=1426949368564 (127.0.0.1) 56.00ms referer=
http://localhost:8888/notebooks/S00_Blaze_Bokeh/bokeh-notebooks/quickstart/quickstart.ipynb
2015-03-21 14:53:15.471 [NotebookApp] WARNING | Unreadable Notebook: C:\Users\Amit\Documents\IPython Notebooks\S00_Blaze_Bokeh\bkh00_quick-start.ipynb
 Notebook does not appear to be JSON: '{\ncells: [\n{\ncell_type: "markdown",\...
WARNING:tornado.access:400 GET /api/notebooks/S00_Blaze_Bokeh/bkh00_quick-start.ipynb?_=1426949594843 (127.0.0.1) 52.00ms referer=http://localhost:888
8/notebooks/S00_Blaze_Bokeh/bkh00_quick-start.ipynb

**Comment by bryevdv** [comment]
What version of IPython notebook are you using?

**Comment by an100** [comment]
C:\Users\Amit>conda info
Current conda install:

             platform : win-64
        conda version : 3.10.0
  conda-build version : 1.8.2
       python version : 3.4.1.final.0
     requests version : 2.6.0
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False


ipython=2.2.0=py34_0
ipython-notebook=2.2.0=py34_0
ipython-qtconsole=2.2.0=py34_0

**Comment by bryevdv** [comment]
I believe the notebooks are now nbformat version 4. Since you are using conda, can you try in an environment with IPython 3?

**Comment by an100** [comment]
Yes. It works. Thanks Bryan! Amit.

**Comment by bryevdv** [comment]
OK good to know, we probably should have thought more carefully about updating the nbformat but I am not sure there is any going back now.
