### ISSUE TITLE
[Binder] 02 - Styling and Theming: RuntimeError data directory does not exist

### ISSUE THREAD

**Issue by adrienpacifico** [bokeh/bokeh-notebooks#60]
### Problem
The 02 - Styling and Theming breaks at cell `[10]`.

<details>
  <summary>Full error</summary>
  <p>

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-9b6655e825c9> in <module>()
      1 from bokeh.models.tools import HoverTool
----> 2 from bokeh.sampledata.glucose import data
      3 
      4 subset = data.loc['2010-10-06']
      5 

/srv/conda/lib/python3.6/site-packages/bokeh/sampledata/glucose.py in <module>()
     55 #-----------------------------------------------------------------------------
     56 
---> 57 data = external_csv('glucose', 'CGM.csv', sep=',', parse_dates=[1], index_col=1)

/srv/conda/lib/python3.6/site-packages/bokeh/util/api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

/srv/conda/lib/python3.6/site-packages/bokeh/util/sampledata.py in external_csv(module, name, **kw)
     93     '''
     94     pd = import_required('pandas', '%s sample data requires Pandas (http://pandas.pydata.org) to be installed' % module)
---> 95     return pd.read_csv(external_path(name), **kw)
     96 
     97 @dev((1,0,0))

/srv/conda/lib/python3.6/site-packages/bokeh/util/api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

/srv/conda/lib/python3.6/site-packages/bokeh/util/sampledata.py in external_path(filename)
    130 @dev((1,0,0))
    131 def external_path(filename):
--> 132     data_dir = external_data_dir()
    133     fn = join(data_dir, filename)
    134     if not exists(fn) and isfile(fn):

/srv/conda/lib/python3.6/site-packages/bokeh/util/api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

/srv/conda/lib/python3.6/site-packages/bokeh/util/sampledata.py in external_data_dir(create)
    116     if not exists(data_dir):
    117         if not create:
--> 118             raise RuntimeError('bokeh sample data directory does not exist, please execute bokeh.sampledata.download()')
    119         print("Creating %s directory" % data_dir)
    120         try:

RuntimeError: bokeh sample data directory does not exist, please execute bokeh.sampledata.download()

```
</p></details>

### Bad fix
```python
import bokeh
bokeh.sampledata.download()
```
Obviously solve the issue, but I guess it is a binder configuration file that would sort things out.

**Comment by bryevdv** [comment]
I am not aware of any way to configure binder to have that directory "just be available" or have that command run automatically, though I would-be pleased to learn otherwise

**Comment by adrienpacifico** [comment]
Sorry, I was probably unclear in the issue.

1. The notebook breaks at cell [10] saying that you have to download sampledata
2. If you download the data in the notebook by running `bokeh.sampledata.download()`, then the notebook run smoothly.
3. I have no idea why this is happening, the issue is not present in the 00 notebook.

**Comment by bryevdv** [comment]
I understood our description, I'm just not aware of any solution at all beyond the one you labeled "bad fix"

> I have no idea why this is happening, the issue is not present in the 00 notebook.

Very small data sets are bundled directly with the package itself. Larger ones have to be downloaded. This will only show up if you try to run code that depends on one of the large data sets, which presumably there are none that do in the other notebooks.

**Comment by adrienpacifico** [comment]
Ok, binder documentation refers to [post-build](http://mybinder.readthedocs.io/en/latest/using.html#postbuild) that would (I guess) allow to run a python script to download sample data.

**Comment by bryevdv** [comment]
Oh, that might work then. Would you mind making a PR to add that script, and have it run `bokeh sampledata download`?

**Comment by adrienpacifico** [comment]
Hi @bryevdv ,
I'm unsure about the time it would take, and I try to avoid task with uncertain cost (as I have a thesis to finish), I'll spend 30 minutes on it today, If I can't make it work then I'll just give up.


By the way, it might increase the time needed to open the binder by 10.6 seconds .

You may want think about the tradeoff between 11 seconds for all users and an Error for users that goes up to notebook 02 (and where most of them will be able to solve the issue).

One solution would be to modify the [download()](https://github.com/bokeh/bokeh/blob/5711a13b2067f350dbae1f39584cb0b1cef1c216/bokeh/util/sampledata.py#L57) function with an optional argument name for the needed dataset (e.g. `download(sample = "glucose")` ).

**Comment by adrienpacifico** [comment]
See #61 

In the end, launching binder is not significantly longer than before.

**Comment by bryevdv** [comment]
Merged, thanks!
