### ISSUE TITLE
11. Running Bokeh applications

### ISSUE THREAD

**Issue by JuanInATrillion** [bokeh/bokeh-notebooks#63]
Hi Bryan, having issues with 11. Running Bokeh applications, only when embedding in Jupyter notebooks. 
At show(modify_doc) I get the following exception: 
AttributeError: 'function' object has no attribute 'references'
This also occurs when I pass notebook_url="http://localhost:8888". 

My bokeh version is 0.12.10, iPython ver 6.1.0, Python 3.6.3
Any help is appreciated here. 
Thank you.

**Comment by bryevdv** [comment]
Hi, 0.12.10 is too old for the latest versions of the notebook (the ability to pass a function to `show` was added *after* 0.12.10). You will have to explicitly check out older versions of these notebooks from around the time 0.12.10 was released to see the older more explicit way of doing things, or update your Bokeh version to something newer.
