### ISSUE TITLE
Cleanup pointers to more info and contacts

### ISSUE THREAD

**Issue by timsnyder** [bokeh/bokeh-notebooks#67]
Simplify the pointers to more info and contacts to link to the toplevel "brand" page bokeh.org instead of duplicating that info across all of the bokeh repos.

**Comment by bryevdv** [comment]
This would be great. I hope to be able to load the actual header/footer code dynamically across all the sites, but we will see. In any case it's definitely time to move any project global/static information to bokeh.org and have everything link there

**Comment by timsnyder** [comment]
I don't mind trying to change the header/footer but I'll do that in a separate ticket in case it ends up being more involved.

**Comment by bryevdv** [comment]
Well for notebooks I my comment was mostly about links, AFAIK the nbviewer an my binder sites don't offer control over the page format. Or do you mean in the notebooks themselves? That might be cool but definitely a follow on, I agree. Let's get the sites we have more consolidated first (after the RTD docs move too, for sure)

**Comment by timsnyder** [comment]
I was talking about the other sites and I see how that was confusing in a ticket about the notebooks.

Are the notebooks supposed to have output cells checked into github?  I've just been tweaking them by hand and I was surprised that some of them have output cells checked in.

**Comment by bryevdv** [comment]
*These* notebooks are, that's why this repository exists separately. These are used as source material for mybinder, which is live notebooks, but also for the nbviewer site, which only renderers static notebooks (i.e. need output cells already)

**Comment by timsnyder** [comment]
Okay.  Makes sense.  I for some reason I thought nbviewer did the rendering.

Would you like a commit with only the input changes and then another with the output changes to make it easier to look through?  I haven't seen how github renders the diff.  Maybe it uses nbdime and splitting the changes isn't needed?

**Comment by bryevdv** [comment]
Fo this repo I am happy to accept whatever changes are simplest/easiest for you :)
