### ISSUE TITLE
update tutorial/10 - Exporting and Embedding for CSS changes in 2.0

### ISSUE THREAD

**Issue by timsnyder** [bokeh/bokeh-notebooks#68]
tutorial 10 explicitly links in the CSS from cdn.pydata.org.  When we stop having the empty CSS files there, it will break.

Also, the version of the CSS and JS being linked in the tutorial is old.  Probably need to search for 'bokeh-\d+\.\d+\.\d+' and replace it with the version set in envioronment.yml

**Comment by bryevdv** [comment]
We can/should also update to `cdn.bokeh.org` which is the new URL to use (old pydata URLs will stay working though)

**Comment by sbrice** [comment]
"good first issue"? That domain will be active for the foreseeable future, right? (I'm thinking long-term as-in having a "Bokeh Introductory Sprint" later in the year)

**Comment by bryevdv** [comment]
The `cdn.pydata.org` domain needs to be active indefinitely, yes, but we should update links wherever we can. It would certainly be a good first issue but I'm also not sure I'd want to wait long for someone new to chow up and do it by chance.
