### ISSUE TITLE
Tutorial 5 - Presentation and Layout

### ISSUE THREAD

**Issue by GuilhermeADF** [bokeh/bokeh-notebooks#76]
Tutorial number 5 (Presentation and Layout) has the following exercise:

> `In [4]:` # EXERCISE: use column to arrange a few plots vertically

When doing this exercise it took me some time to realise that I had to import `column`.

I think the tutorial can be improved for new users if either the import is already in the code: `from bokeh.layouts import row, column` 

or, probably even better because it makes the user take action, if the exercise remembers the user that he has to import `column`, for example:

> `In [4]:` # EXERCISE: use column to arrange a few plots vertically. Don't forget to import `column`.

**Comment by bryevdv** [comment]
@GuilhermeADF  Sounds good, happy to accept a PR
