### ISSUE TITLE
Slider on graph in tutorial/00 - intro.ipynb does not work with python 2

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh-notebooks#8]
@birdsarah, I noticed that when I run *bubble_plot.py* with python 2, the slider doesn't work.  Looking at the debugger, this seems to be a unicode issue.  It's trying to look up "u_1964" when the actual key is "_1964."

**Comment by birdsarah** [comment]
Thanks @Maggie-M - I've been using python3 - that's interesting.

**Comment by birdsarah** [comment]
should be fixed by d6b185ce12e798b05a3d59be4a32af8bec6b7cf7. Can you check it out?

**Comment by Maggie-M** [comment]
Sure, I'll check it out.

Thanks!
