### ISSUE TITLE
i 've Error help me

### ISSUE THREAD

**Issue by KOOKDONGHUN** [bokeh/bokeh-notebooks#83]
from math import pi
from bokeh.sampledata.glucose import data

week = data.loc['2010-10-01':'2010-10-08']

p = figure(x_axis_type="datetime", title="Glocose Range", plot_height=350, plot_width=800)
p.xaxis.formatter.days = '%m/%d/%Y'
p.xaxis.major_label_orientation = pi/3

p.line(week.index, week.glucose)

show(p)

this code have AttributeError: '_list_attr_splat' object has no attribute 'formatter'
I want solution please

**Comment by xavArtley** [comment]
Works pretty well
![image](https://user-images.githubusercontent.com/18531147/80597065-9f592a80-8a27-11ea-8b3b-b1aef1716306.png)

**Comment by bryevdv** [comment]
@KOOKDONGHUN please visit the Project Discourse for help and support questions:

https://discourse.bokeh.org/
