### ISSUE TITLE
five minute overview: linked brushing example throws error 

### ISSUE THREAD

**Issue by EricThomson** [bokeh/bokeh-notebooks#88]
In `quickstart.ipynb`, for the Linked Brushing example, when I run the following line:

`source = ColumnDataSource(autompg)`

I get the following error:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-28-739c30097d6e> in <module>
> ----> 1 source = ColumnDataSource(autompg)
> 
> ~\Miniconda3\envs\ds\lib\site-packages\bokeh\models\sources.py in __init__(self, *args, **kw)
>     192                 raw_data = self._data_from_groupby(raw_data)
>     193             else:
> --> 194                 raise ValueError("expected a dict or pandas.DataFrame, got %s" % raw_data)
>     195         super().__init__(**kw)
>     196         self.data.update(raw_data)
> 
> ValueError: expected a dict or pandas.DataFrame, got       mpg  cyl  displ   hp  weight  accel  yr  origin  \

autompg is a dataframe that worked fine for the previous bar plot example.  I am running Bokeh 2.1.0, in a Jupyter Notebook using conda (Python 3.7).

**Comment by bryevdv** [comment]
@EricThomson Please provide all the relevant package versions for your local setup

**Comment by EricThomson** [comment]
pandas 1.0.5, numpy 1.18.1, ipython 7.14, jupyter notebook 6.03, jupyter core 4.6.3.

**Comment by EricThomson** [comment]
Sorry just re-ran everything from scratch and did not get the error. Have no idea what changed, but it looks good now.
