### ISSUE TITLE
demo chart in "basic plotting" is not working 

### ISSUE THREAD

**Issue by curlup** [bokeh/bokeh-notebooks#91]
![Screen Shot 2020-09-28 at 4 31 48 PM](https://user-images.githubusercontent.com/338607/94483022-39c0c400-01a8-11eb-9345-4c719b73dc00.png)

**Comment by bryevdv** [comment]
There are some sets of circumstances that can trigger CORS issues when loading BokehJS. See https://github.com/bokeh/bokeh/issues/9773 for full details. 

TLDR; you will need to clear cache / force-reload.
