### ISSUE TITLE
tutorial for a dynamic update of 2D image content

### ISSUE THREAD

**Issue by lorcat** [bokeh/bokeh-notebooks#95]
Hi!
Sorry for bothering and many thanks for bokeh!

I would greatly appreciate if anyone could help me recolving an issue.
It is clear how one can update contents of a 1D graph in a dynamic fashion - upon events, but updating 2D images content - is not clear. Here I am refering to the updates of 2D images shown with p.image(image=[np.array(..)],level="image").

I have tried to do the following without any success. Would it be possible to make an example notebook?
I am providing a simple code I tried.

`
from bokeh.layouts import column, row
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, Select, TextInput

def simple_app(doc):
    
    p = figure(tools="", toolbar_location=None)
    
    p = figure(tooltips=[("x", "$x"), ("y", "$y"), ("value", "@image")])
    p.x_range.range_padding = p.y_range.range_padding = 0
    
    r = p.image(image=[np.zeros((200,200))], x=0, y=0, dw=10, dh=10, palette="Spectral11", level="image")
    
    select = Select(title="Select data", value="file2", options=['file1','file2'])
    
    def update_data(attrname, old, new):
        tdata = {"file1": np.random.rand(200,200)*3,
                 "file2": np.random.rand(200,200)*5.,
                }
        # reading files        
        cd = ColumnDataSource(data={'image': tdata[select.value]})
        print(f"Selected {select.value}")
        r.data_source = cd
    
    select.on_change('value', update_data)

    layout = column(row(select, width=200), row(p))

    doc.add_root(layout)

show(simple_app)
`

**Comment by bryevdv** [comment]
@lorcat For support/useage questions, please use the community [Discourse site](https://discourse.bokeh.org)
