### ISSUE TITLE
error without message

### ISSUE THREAD

**Issue by MalikRumi** [bokeh/bokeh-notebooks#98]
I have a red error box showing up at the top of my notebook - which has now become unresponsive. This is on the navbar, I guess, to the right of "Widgets   Help". But there is no message, no explanation, no pop up, no nothing. What am I supposed to do with that? How would I know if the issue is bokeh, binder, or some dependency? I've got **nothing** to go on here!!!  https://notebooks.gesis.org/binder/jupyter/user/bokeh-bokeh-notebooks-lmhpedwb/notebooks/tutorial/01%20-%20Basic%20Plotting.ipynb#

**Comment by bryevdv** [comment]
What is the error? Please always provide the actual text of error messages (or a screenshot if copying text is not possible). Without more information we have nothing to speculate with. Are there any error messages in your browsers JS console?

I am not sure why you are having such difficulty with binder. I just ran through all the cells in the Basic Plotting notebook on binder and everything works as expected without any issue:

<img width="939" alt="Screen Shot 2022-04-29 at 07 50 47" src="https://user-images.githubusercontent.com/1078448/165969010-b34c7ecf-b134-4f6c-9420-690dfb1dd616.png">
<img width="922" alt="Screen Shot 2022-04-29 at 07 50 56" src="https://user-images.githubusercontent.com/1078448/165969017-dff465b8-64d7-4156-b5e6-547320396471.png">

**Comment by bryevdv** [comment]
> This is on the navbar, I guess, to the right of "Widgets Help".

FYI if it is on the navbar then the error is not coming from Bokeh. Did you leave the page idle for a long time? AFAIK Binder will disconnect dormant sessions after some time of inactivity. Alternatively, perhaps the connection never successfully initiates. But if so, that would be an issue with Binder, or your network setup (maybe a firewall blocking websockets?), that we will not be able to do anything about. Perhaps you would have an easier time running the tutorial notebook locally.

**Comment by MalikRumi** [comment]
>>> What is the error?
1. There is no error message
>>>Are there any error messages in your browsers JS console?
2. I have no idea. I'll have to check next time. Something to look forward
to.....
>>>AFAIK Binder will disconnect dormant sessions after some time of
inactivity.
3. Well, I can try to get help from them, but what has timing out got to do
with not being allowed back in *at all?*
>>>, or your network setup (maybe a firewall blocking websockets?
4. At the moment, I am in the hospital library, but I doubt that is the
issue since I have already had *exactly* this same experience when I was
working from home both last night and this morning.
>>>Perhaps you would have an easier time running the tutorial notebook
locally.
5. I can try that, but: aren't these one-at-a-time separate notebooks? Is
there a way to download them all at once? Will there be any connection,
resource, or path issues running the notebooks locally instead of online as
intended?


*“None of you has faith until he loves for his brother or his neighbor what
he loves for himself.”*

**Comment by bryevdv** [comment]
> 1. There is no error message

I don't understand how this is consistent with your earlier statement:

> I have a red error box showing up at the top of my notebook 

What in the error box? How do you know it is an error box if there is not some error text? Regardless, it's not something coming from Bokeh, so it's not something we will be able to address. 

> 3. Well, I can try to get help from them, but what has timing out got to do with not being allowed back in *at all?*

You have to go back to the *original* tutorial links, to start up a new session. That's the way binder works. When you click the original links, Binder spins up a VM to service a new session for and redirects you to a unique temporary URL for that session. When things time out, and Binder shuts down the VM then the session URL becomes useless. Again: this has nothing to do with Bokeh. This is just how Binder works and we have not control over that whatsoever. 

> I can try that, but: aren't these one-at-a-time separate notebooks? Is there a way to download them all at once? 

The simplest way to get the notebooks locally is to `git clone` this repo. 

> Will there be any connection, resource, or path issues running the notebooks locally instead of online as
intended?

You'll need to set up a suitable environment with Bokeh, JupyterLab, etc. intstalled. There is a conda env file that lists all the dependencies here: https://github.com/bokeh/bokeh-notebooks/blob/main/environment.yml

**Comment by bryevdv** [comment]
I think the take-away might be this. If your session times out, you always have to go back to this URL:

https://mybinder.org/v2/gh/bokeh/bokeh-notebooks/master?filepath=tutorial%2F00%20-%20Introduction%20and%20Setup.ipynb

You cannot go back to the "notebooks.gesis.org" links. Those are ephemeral, and once the session is shut down they are not usable.

**Comment by bryevdv** [comment]
xref: https://discourse.bokeh.org/t/jupyter-hub-403-forbidden/9132

**Comment by bryevdv** [comment]
I am going to go ahead and close this as I don't think there is any action to take on our end.

**Comment by MalikRumi** [comment]
*“None of you has faith until he loves for his brother or his neighbor what
he loves for himself.”*


On Fri, Apr 29, 2022 at 1:42 PM Bryan Van de Ven ***@***.***>
wrote:

>
>    1. There is no error message
>
> I don't understand how this is consistent with your earlier statement:
>
> I have a red error box showing up at the top of my notebook
>
> That's all it was, a little red box with 'error' on it. Nothing else.

> What in the error box? How do you know it is an error box if there is not
> some error text? Regardless, it's not something coming from Bokeh, so it's
> not something we will be able to address.
>
I didn't save it at the time, but it was here, just to the left of the
'trusted / not trusted' box:
[image: Screenshot from 2022-05-01 13-49-38.png]
